# Generated by Django 5.2 on 2025-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="preferences",
            field=models.JSONField(default=list),
        ),
    ]
